version: "3"

volumes:
  node_modules:
services:
  missing-pets-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3001:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
